### PR TITLE
Disable nullable context in the file

### PR DESCRIPTION
**Pull request by kzu**
Workaround for #42 by just disabling nullable context entirely for the entire file.

Potential improvement would be to actually properly annotate with nullable and fix whatever nullable errors are raised after enabling it.

### CODE REVIEW

**Comment by kzu** [comment]
Hm... I guess it's not as simple. This will not build (apparently) on MSBuild15/VS2017 and prior :(

**Comment by stakx** [comment]
@kzu I ran a quick experiment by replacing the `Copy` task in the `.targets` file:

https://github.com/stakx/TypeNameFormatter/blob/08a2de8779180c4a6b7d70ab7642d381f95da1bd/src/TypeNameFormatter/TypeNameFormatter.Sources.targets#L33

with a combination of [`ReadLinesFromFile`](https://docs.microsoft.com/en-us/visualstudio/msbuild/writelinestofile-task?view=vs-2019) and [`WriteLinesToFile`](https://docs.microsoft.com/en-us/visualstudio/msbuild/writelinestofile-task?view=vs-2019):

```xml
    <WriteLinesToFile File="$(BaseIntermediateOutputPath)TypeNameFormatter.cs" Lines="" Overwrite="True" />
    <WriteLinesToFile File="$(BaseIntermediateOutputPath)TypeNameFormatter.cs" Condition="'$(TypeNameFormatterNullableDisable)' == 'True'" Lines="#nullable disable" Overwrite="False" />
    <ReadLinesFromFile File="$(SourceFolder)TypeNameFormatter.cs">
      <Output TaskParameter="Lines" ItemName="TypeFormatterLinesOfCode" />
    </ReadLinesFromFile>
    <WriteLinesToFile File="$(BaseIntermediateOutputPath)TypeNameFormatter.cs" Lines="@(TypeFormatterLinesOfCode)" Overwrite="False" />
```

and I added a new property `<TypeNameFormatterNullableDisable>` (defaults `False`) that you can set to `True` in your project file.

It works... sort of. There are two annoying details that make this a less-than-ideal solution:

* `WriteLinesToFile` completely destroys indentation.
* If you change the value of `<TypeNameFormatterNullableDisable>` in your own project file, the intermediate `TypeNameFormatter.cs` doesn't get regenerated.

**Comment by kzu** [comment]
Interesting. I think I would default the property to true if `$(Nullable)!='disable'`. It's counter-intuitive that you're disabling nullable in the file if nullable is *not* disabled in the project, but that's precisely what you need to do anyway 🤔

**Comment by stakx** [comment]
What I'm not entirely clear about is how to determine in MSBuild whether or not the compiler supports `#nullable`. What if `<Nullable>` is simply not set at all? Does one query `<LangVersion>` next? Or the MSBuild tools version or install path? Or something else altogether?

**Comment by kzu** [comment]
I'm pretty sure unless you have a non-empty value for $(Nullable), it will not be turned on for the compiler. I think it's safe to assume that if you set *some* value there, it's because you have a nullable-capable compiler, right?

**Comment by stakx** [comment]
Yes, that makes sense. Let's hope it really is that simple for a change.

How about we duplicate the main code file and add `#nullable disable` there (or even better, `#nullable enable` and actual nullable annotations)?

I hate the duplicated code, but I think it's better and more flexible than the MSBuild contortion I demonstrated above.

**Comment by kzu** [comment]
I think the simpler the better. I'm done with T4, I love Scriban now :)

**Comment by stakx** [comment]
Closing this PR in favor of #44.

**Pull request closed without merging**
